branch-defaults:
  default:
    environment: kiosk-dev-env
    group_suffix: null
global:
  application_name: kiosk-dev
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: applestone-dev
  repository: null
  sc: null
  workspace_type: Application
